# Generated by Django 2.2 on 2019-04-23 21:47

import django_models_from_csv.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('csv_url', models.URLField(blank=True, null=True)),
                ('columns', django_models_from_csv.fields.ColumnsField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
