# Generated by Django 2.2 on 2019-05-09 18:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodel',
            name='attrs',
            field=jsonfield.fields.JSONField(default=dict, max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamicmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
