# Generated by Django 2.2 on 2019-05-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0002_auto_20190509_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicmodel',
            options={'verbose_name': 'Successful Import', 'verbose_name_plural': 'Successful Imports'},
        ),
        migrations.AddField(
            model_name='dynamicmodel',
            name='sd_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmodel',
            name='sd_form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmodel',
            name='sd_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
