# Generated by Django 2.2.2 on 2019-06-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0005_dynamicmodel_csv_google_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicmodel',
            name='token',
        ),
    ]
