# Generated by Django 2.2 on 2019-08-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0006_remove_dynamicmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodel',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='csv_uploads/'),
        ),
    ]
