# Generated by Django 2.2 on 2019-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0008_auto_20190830_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('credentials', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dynamicmodel',
            name='csv_google_credentials',
        ),
    ]
