# Generated by Django 2.2.9 on 2020-02-20 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_models_from_csv', '0009_auto_20190905_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundRefreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(default="Background importer hasn't run for this data source, yet. If this message persists for more than a few days, then the background updater hasn't been installed. See here for more information: https://github.com/propublica/django-collaborative/blob/master/docs/launching-collaborate.md")),
                ('dynmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_models_from_csv.DynamicModel')),
            ],
        ),
    ]
