# Generated by Django 2.2 on 2019-04-17 05:24

import collaborative.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('share_url', models.URLField(blank=True, null=True)),
                ('columns', collaborative.fields.ColumnsField(blank=True, null=True)),
            ],
        ),
    ]
