# Generated by Django 2.2 on 2019-05-03 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=120)),
                ('method', models.IntegerField(choices=[(0, 'Email'), (1, 'Phone call'), (2, 'In person')])),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'In Progress'), (2, 'Verified'), (3, 'Troll'), (4, 'Duplicate'), (5, 'Not Applicable'), (6, 'Inconclusive'), (7, 'False')], default=0)),
                ('partner', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ManyToManyField(to='collaborative.Contact')),
            ],
        ),
    ]
